NOTE_MAP = {
  76 => 80,   # Crash Cymbal EFX (Choke) -> High Crash - Choke
  75 => 78,   # Crash Cymbal 4 (Choke) -> Low Crash - Choke
  74 => 71,   # Tom 1 R -> Tom 1 - Center R
  73 => 82,   # Crash Cymbal 3 (Choke) -> China - Choke
  72 => 69,   # Tom 2 R -> Tom 2 - Center R
  71 => 67,   # Tom 3 R -> Tom 3 - Center R
  70 => 90,   # Splash Cymbal (Choke) -> Splash - Choke
  69 => 65,   # Floor Tom 1 R -> Tom 3 - Center R (double)
  68 => 79,   # Crash Cymbal 2 -> High Crash - Edge
  67 => 65,   # Floor Tom 2 R -> Tom 3 - Center R (double)
  66 => 80,   # Crash Cymbal 1 (Choke) -> High Crash - Choke
  65 => 65,   # Floor Tom 2 R (Copy) -> Tom 3 - Center L/R (double)
  64 => 40,   # Snare Rimshot R -> Snare - Wires Off
  63 => 81,   # China 2 Cymbal -> China - Edge
  62 => 40,   # Snare R -> Snare Flam
  61 => 79,   # Crash EFX -> High Crash - Tip
  60 => 61,   # Bell Cymbal -> Ride - Bell
  59 => 79,   # Crash Cymbal 4 -> High Crash - Edge
  58 => 81,   # Crash Cymbal 3 -> China - Tip
  57 => 79,   # Crash Cymbal 2 -> High Crash - Edge
  56 => 100,  # Cowbell -> Cowbell Hi - Open
  55 => 89,   # Splash Cymbal -> Splash - Edge
  54 => 96,   # Tambourine -> Tambourine - Shake
  53 => 61,   # Ride Cymbal Bell -> Ride - Bell
  52 => 81,   # China 1 Cymbal -> China - Edge
  51 => 60,   # Ride Cymbal Center -> Ride - Tip
  50 => 71,   # Tom 1 L -> Tom 1 - Center R
  49 => 79,   # Crash Cymbal 1 -> High Crash - Edge
  48 => 69,   # Tom 2 L -> Tom 2 - Center R
  47 => 67,   # Tom 3 L -> Tom 3 - Center L
  46 => 54,   # Hat Open TIP -> Open Hihat - Control
  45 => 65,   # Floor Tom 1 L -> Tom 3 - Center L (double)
  44 => 48,   # Hat Foot Close -> Closed Hihat - Pedal
  43 => 65,   # Floor Tom 2 L -> Tom 3 - Center L/R (double)
  42 => 52,   # Hat Closed TIP -> Closed Hihat - Tip L/R
  41 => 65,   # Floor Tom 2 L (Copy) -> Tom 3 - Center L/R (double)
  40 => 37,   # Snare Rimshot L -> Snare - Rimshot
  39 => 47,   # Hand Clap -> Clap - Multi
  38 => 38,   # Snare L -> Snare - Center L/R
  37 => 42,   # Side Stick -> Snare - Sidestick
  36 => 36,   # Kick 1 -> Kick - Dampened
  35 => 36,   # Kick 1 Buried -> Kick - Dampened
  34 => 54,   # Hat Open SHANK -> Open Hihat - Control
  33 => 54,   # Hat ExtraOpen TIP -> Open Hihat - Control
  32 => 53,   # Hat Foot Open -> Open Hihat - Pedal
  31 => 54,   # Hat ExtraOpen SHANK -> Open Hihat - Control
  30 => 50,   # Hat Closed SHANK -> Closed Hihat - Shank L
  29 => 50,   # Hat Tight Closed TIP -> Closed Hihat - Tight Tip L
  28 => nil,  # - (no sound)
  27 => 50,   # CC TIP -> Closed Hihat - Tip L
  26 => nil,  # - (no sound)
  25 => 50,   # CC SHANK -> Closed Hihat - Shank L
  24 => nil,  # - (no sound)
  23 => 36,   # Kick 2 Buried -> Kick - Dampened
  22 => 36    # Kick 2 -> Kick - Dampened
}
